#!/usr/bin/env python3

from random import randint

# Small limits: Python can't handle the above limits (without external libs)
# See bignum_Fermat.c for a C version using the GMP library
l_limit=10
u_limit=1000

while True:
    # 1. choose a random integer within limits
    r = randint(l_limit, u_limit)
    # 2. test [ 2**(p-1) == 1 in Zp ]? If True, stop
    # Otherwise, go back to 1.
    if ((2 ** (r-1))%r) == 1:
        print(r)
        break

