#!/usr/bin/env python3

# Keeps generating primes sequentially until Crl-C is pressed

def main():
    def isprime(a):
        return not (a < 2 or any(a % x == 0 for x in range(2, int(a ** 0.5) + 1)))

    counter = 1

    while True: 
        if isprime(counter) == True:
          print(counter, end=', ')
        counter += 1

if __name__ == "__main__":
    main()
